version: "3.8"

services:
  # reactjs-client:
  #   image: reactjs-client
  #   stdin_open: true
  #   ports:
  #     - "3000:3000"
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server/src:/app/src
    depends_on:
      - mongo
    command: >
      sh -c "npm start"
  mongo:
    container_name: mongo
    image: mongo:4.4.6
    restart: always
    volumes:
      - ~/mongo:/data/db
    ports:
      - "27017:27017"
    command: [--auth]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sadman
      - MONGO_INITDB_ROOT_PASSWORD=sadman
      - MONGO_INITDB_DATABASE=database
